var searchData=
[
  ['va_5flist',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['vacuumlogger',['VacuumLogger',['../class_tomographer_1_1_logger_1_1_vacuum_logger.html',1,'Tomographer::Logger']]],
  ['valarray',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map']]],
  ['valuehistogrammhrwstatscollector',['ValueHistogramMHRWStatsCollector',['../class_tomographer_1_1_value_histogram_m_h_r_w_stats_collector.html',1,'Tomographer']]],
  ['valuehistogrammhrwstatscollector_3c_20valuecalculator_2c_20loggertype_2c_20basehistogramtype_20_3e',['ValueHistogramMHRWStatsCollector&lt; ValueCalculator, LoggerType, BaseHistogramType &gt;',['../class_tomographer_1_1_value_histogram_m_h_r_w_stats_collector.html',1,'Tomographer']]],
  ['valuehistogramwithbinningmhrwstatscollector',['ValueHistogramWithBinningMHRWStatsCollector',['../class_tomographer_1_1_value_histogram_with_binning_m_h_r_w_stats_collector.html',1,'Tomographer']]],
  ['valuehistogramwithbinningmhrwstatscollectorparams',['ValueHistogramWithBinningMHRWStatsCollectorParams',['../struct_tomographer_1_1_value_histogram_with_binning_m_h_r_w_stats_collector_params.html',1,'Tomographer']]],
  ['valuehistogramwithbinningmhrwstatscollectorresult',['ValueHistogramWithBinningMHRWStatsCollectorResult',['../struct_tomographer_1_1_value_histogram_with_binning_m_h_r_w_stats_collector_result.html',1,'Tomographer']]],
  ['var',['Var',['../class_tomographer_1_1_m_a_t_1_1_var.html',1,'Tomographer::MAT']]],
  ['varerror',['VarError',['../class_tomographer_1_1_m_a_t_1_1_var_error.html',1,'Tomographer::MAT']]],
  ['varmattypeerror',['VarMatTypeError',['../class_tomographer_1_1_m_a_t_1_1_var_mat_type_error.html',1,'Tomographer::MAT']]],
  ['varreaderror',['VarReadError',['../class_tomographer_1_1_m_a_t_1_1_var_read_error.html',1,'Tomographer::MAT']]],
  ['varshape',['VarShape',['../struct_tomographer_1_1_m_a_t_1_1_var_shape.html',1,'Tomographer::MAT']]],
  ['vartypeerror',['VarTypeError',['../class_tomographer_1_1_m_a_t_1_1_var_type_error.html',1,'Tomographer::MAT']]],
  ['varvaluedecoder',['VarValueDecoder',['../class_tomographer_1_1_m_a_t_1_1_var_value_decoder.html',1,'Tomographer::MAT']]],
  ['varvaluedecoder_3c_20eigen_3a_3amatrix_3c_20scalar_2c_20rows_2c_20cols_2c_20options_2c_20maxrows_2c_20maxcols_20_3e_20_3e',['VarValueDecoder&lt; Eigen::Matrix&lt; Scalar, Rows, Cols, Options, MaxRows, MaxCols &gt; &gt;',['../class_tomographer_1_1_m_a_t_1_1_var_value_decoder_3_01_eigen_1_1_matrix_3_01_scalar_00_01_rows_07d74a4180f13c5cbad1690a7731c877d.html',1,'Tomographer::MAT']]],
  ['varvaluedecoder_3c_20eigenpossemidefmatrixwithsqrt_3c_20eigentype_5f_20_3e_20_3e',['VarValueDecoder&lt; EigenPosSemidefMatrixWithSqrt&lt; EigenType_ &gt; &gt;',['../class_tomographer_1_1_m_a_t_1_1_var_value_decoder_3_01_eigen_pos_semidef_matrix_with_sqrt_3_01_eigen_type___01_4_01_4.html',1,'Tomographer::MAT']]],
  ['varvaluedecoder_3c_20getstdvector_3c_20t_2c_20isrowmajor_20_3e_20_3e',['VarValueDecoder&lt; GetStdVector&lt; T, IsRowMajor &gt; &gt;',['../class_tomographer_1_1_m_a_t_1_1_var_value_decoder_3_01_get_std_vector_3_01_t_00_01_is_row_major_01_4_01_4.html',1,'Tomographer::MAT']]],
  ['varvaluedecoder_3c_20std_3a_3avector_3c_20eigen_3a_3amatrix_3c_20scalar_2c_20rows_2c_20cols_2c_20options_2c_20maxrows_2c_20maxcols_20_3e_2c_20alloc_20_3e_20_3e',['VarValueDecoder&lt; std::vector&lt; Eigen::Matrix&lt; Scalar, Rows, Cols, Options, MaxRows, MaxCols &gt;, Alloc &gt; &gt;',['../class_tomographer_1_1_m_a_t_1_1_var_value_decoder_3_01std_1_1vector_3_01_eigen_1_1_matrix_3_01_sc28408501a97be3b5738be4dde0ca8cd.html',1,'Tomographer::MAT']]],
  ['varvaluedecoder_3c_20t_2c_20_5fis_5fnumeric_5ftype_20_3e',['VarValueDecoder&lt; T, _IS_NUMERIC_TYPE &gt;',['../class_tomographer_1_1_m_a_t_1_1_var_value_decoder_3_01_t_00_01___i_s___n_u_m_e_r_i_c___t_y_p_e_01_4.html',1,'Tomographer::MAT']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20bool_20_3e',['vector&lt; bool &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20int_20_3e',['vector&lt; int &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20inttype_20_3e',['vector&lt; IntType &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aexception_5fptr_20_3e',['vector&lt; std::exception_ptr &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20taskresulttype_20_2a_3e',['vector&lt; TaskResultType *&gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20taskstatusreporttype_2c_20typename_20tools_3a_3aneedownoperatornew_3c_20taskstatusreporttype_20_3e_3a_3aallocatortype_20_3e',['vector&lt; TaskStatusReportType, typename Tools::NeedOwnOperatorNew&lt; TaskStatusReportType &gt;::AllocatorType &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vectorblock',['VectorBlock',['http://eigen.tuxfamily.org/dox/classEigen_1_1VectorBlock.html',1,'Eigen']]],
  ['vectorwiseop',['VectorwiseOp',['http://eigen.tuxfamily.org/dox/classEigen_1_1VectorwiseOp.html',1,'Eigen']]]
];
