
dist: trusty
sudo: required

# Enable C++ support
language: cpp

# Install dependencies
install:
  - pwd
  - export OUR_TRAVIS_PATH=`pwd`
  # Eigen3: need >= 3.3
  - export EIGEN_PATH=`pwd`/eigen-3.3.1
  - if [ ! -f "$EIGEN_PATH/Eigen/src/Core/util/Macros.h" ]; then curl -L https://bitbucket.org/eigen/eigen/get/3.3.1.tar.gz -o eigen-3.3.1.tar.gz && tar xfz eigen-3.3.1.tar.gz && mkdir -p eigen-3.3.1 && mv eigen-eigen-f562a193118d/* eigen-3.3.1 ; fi
  # MatIO:
  - export MATIO_PATH=`pwd`/matio-1.5.9
  - if [ ! -f "$MATIO_PATH/_install/include/matio.h" ]; then curl -L -o matio-1.5.9.tar.gz  https://sourceforge.net/projects/matio/files/matio/1.5.9/matio-1.5.9.tar.gz/download  && tar xfz matio-1.5.9.tar.gz && ( cd matio-1.5.9 && ./configure --prefix="$MATIO_PATH/_install" && make && make install ) ; fi
  # CMake:
  - export CMAKE_PATH=`pwd`/cmake-3.1.3-Linux-x86_64
  - if [ ! -f "$CMAKE_PATH/bin/cmake" ]; then curl -L -O https://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz && tar xfz cmake-3.1.3-Linux-x86_64.tar.gz ; fi
  # PyBind11:
  - export PYBIND11_PATH=`pwd`/pybind11-2.1.0
  - if [ ! -f "$PYBIND11_PATH/_install/include/pybind11/pybind11.h" ]; then curl -L https://github.com/pybind/pybind11/archive/v2.1.0.tar.gz | tar xz && (mkdir -p "$PYBIND11_PATH/build" && cd "$PYBIND11_PATH/build" && cmake .. -DPYBIND11_TEST=0 -DCMAKE_INSTALL_PREFIX="$PYBIND11_PATH/_install" && make install) ; fi
  # Python dependencies
  # hack for preventing travis to interrupt after 10min of no output -- see
  # https://github.com/travis-ci/travis-ci/issues/6591
  - function write_visual_bells() { while true; do echo -en "\a"; sleep 10; done; }; write_visual_bells &
  - sudo -H $PIP install urllib3[secure] # needed for pip upgrade, ...
  - $PIP install --user --upgrade pip # ... upgrade which is needed for --cache-dir :( ...
  - (mkdir -p pip_sandbox && cd pip_sandbox && CC=${PIP_CC=gcc} CXX=${PIP_CXX=g++} ~/.local/bin/pip install --cache-dir=$OUR_TRAVIS_PATH/pip_cache/$PYTHON_EXECUTABLE --user $PIP_EXTRAS wheel cvxpy pybind11 >pip_output.txt 2>&1 || cat pip_output.txt )

cache:
  directories:
    - eigen-3.3.1
    - matio-1.5.9/_install
    - pybind11-2.1.0/_install
    - cmake-3.1.3-Linux-x86_64
    - pip_cache


# Allow git-describe to find the right version string, otherwise the build fails
git:
  depth: 150


# Build steps
script:
  - mkdir build
  - cd build
  - $CMAKE_PATH/bin/cmake .. -DCMAKE_C_COMPILER=$CMAKE_C_COMPILER -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER $CMAKE_COMPILER_ARGS -DBUILD_TOMOPY=on -DTOMOGRAPHER_ENABLE_TESTS=on -DTOMOGRAPHER_TEST_SETUPPY_BUILD=on -DEIGEN3_INCLUDE_DIR="$EIGEN_PATH" -DMATIO_INCLUDE_DIR="$MATIO_PATH/_install/include" -DMATIO_LIBRARY="$MATIO_PATH/_install/lib/libmatio.so" -DCMAKE_FIND_ROOT_PATH="$PYBIND11_PATH/_install" -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE  || cat build/CMakeFiles/CMakeError.log
  - make VERBOSE=1
  # use python/setup.py to build a source package and to compile the extension a first time -- just to make sure it works
  - (cd ../py; CC=$CMAKE_C_COMPILER CXX=$CMAKE_CXX_COMPILER CMAKE_CACHE_FILE=../build/CMakeCache.txt $PYTHON_EXECUTABLE setup.py sdist build bdist_egg bdist_wheel  >setup_py_output.txt || cat setup_py_output.txt )
  # make sure that pip can compile & install from the sdist package.  This is the package
  # we want to test in our CTest suite as "setuppy-built".
  - CC=$CMAKE_C_COMPILER CXX=$CMAKE_CXX_COMPILER $PIP install --user ../py/dist/tomographer-*.tar.gz
  #
  #- export TOMOGRAPHER_PYTHONPATH=... # no longer needed -- pick up installed version
  - CTEST_OUTPUT_ON_FAILURE=1 BOOST_TEST_LOG_LEVEL=all $CMAKE_PATH/bin/ctest --timeout 480

matrix:
  include:
    # ### Dropping support for gcc 4.6 (especially for pybind11)
    #
    # ### Still support g++ 4.8
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - gfortran
            - gfortran-multilib
            - python-dev
            - python-numpy
            - python-scipy
            - python-matplotlib
            - python-tk
            - python-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost1.55-all-dev
            - libboost1.55-dev
      env:
        - CMAKE_C_COMPILER=gcc-4.8
        - CMAKE_CXX_COMPILER=g++-4.8
        - PYTHON_EXECUTABLE=/usr/bin/python
        - CMAKE_COMPILER_ARGS="-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DPYTHON_INCLUDE_DIR=/usr/include/python2.7"
        - PIP=/usr/bin/pip
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - gfortran
            - gfortran-multilib
            - python-dev
            - python-numpy
            - python-scipy
            - python-matplotlib
            - python-tk
            - python-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost1.55-all-dev
            - libboost1.55-dev
      env:
        - CMAKE_C_COMPILER=gcc-5
        - CMAKE_CXX_COMPILER=g++-5
        - PYTHON_EXECUTABLE=/usr/bin/python
        - CMAKE_COMPILER_ARGS="-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DTOMORUN_MULTIPROC=sequential  -DTOMORUN_CXX_FLAGS='-DTOMORUN_USE_DEVICE_SEED=1'"
        - PIP=/usr/bin/pip
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran
            - gfortran-multilib
            - python3-dev
            - python3-numpy
            - python3-scipy
            - python3-matplotlib
            - python3-tk
            - python3-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost1.55-all-dev
            - libboost1.55-dev
      env:
        - CMAKE_C_COMPILER=gcc-6
        - CMAKE_CXX_COMPILER=g++-6
        - PYTHON_EXECUTABLE=/usr/bin/python3
        - CMAKE_COMPILER_ARGS=""
        - PIP=/usr/bin/pip3
    - compiler: clang
      addons:
        apt:
          packages:
            - python-dev
            - python-numpy
            - python-scipy
            - python-matplotlib
            - python-tk
            - python-pip
            # to compile cvxpy:
            - gcc
            - g++
            - gfortran
            - gfortran-multilib
            - libatlas-dev
            - libatlas-base-dev
            - libboost1.55-all-dev
            - libboost1.55-dev
      before_install:
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.4 main'
        - sudo apt-get update
        - sudo apt-get install clang-3.4 clang++-3.4
      env:
        - CMAKE_C_COMPILER=clang-3.4
        - CMAKE_CXX_COMPILER=clang++-3.4
        - PYTHON_EXECUTABLE=/usr/bin/python
        - CMAKE_COMPILER_ARGS=""
        - PIP_CC=/usr/bin/gcc
        - PIP_CXX=/usr/bin/g++
        - PIP=/usr/bin/pip
    - compiler: clang
      addons:
        apt:
          packages:
            - libiomp5
            - libiomp-dev
            - python3-dev
            - python3-numpy
            - python3-scipy
            - python3-matplotlib
            - python3-tk
            - python3-pip
            # to compile cvxpy:
            - gcc
            - g++
            - gfortran
            - gfortran-multilib
            - libatlas-dev
            - libatlas-base-dev
            - libboost1.55-all-dev
            - libboost1.55-dev
      before_install:
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        - sudo apt-get update
        - sudo apt-get install clang-3.8 clang++-3.8
      env:
        - CMAKE_C_COMPILER=clang-3.8
        - CMAKE_CXX_COMPILER=clang++-3.8
        - PYTHON_EXECUTABLE=/usr/bin/python3
        - CMAKE_COMPILER_ARGS="-DOpenMP_C_FLAGS='-fopenmp=libiomp5' -DOpenMP_CXX_FLAGS='-fopenmp=libiomp5' -DPYBIND11_CPP_STANDARD='-std=c++11' -DTOMORUN_MULTIPROC='openmp'"
        - PYBIND11_CPP_STANDARD="-std=c++11" # for setup.py
        - PIP_CC=/usr/bin/gcc
        - PIP_CXX=/usr/bin/g++
        - PIP=/usr/bin/pip3

# No e-mail notifications
notifications:
  email: false
