
# more recent distro - Ubuntu 14.04
sudo: required
dist: trusty

# Enable C++ support
language: cpp

# Compiler selection
#compiler:
#  - clang
#  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. -DTOMOGRAPHER_ENABLE_TESTS=on && make && make test


matrix:
  include:
    - compiler: gcc
      addons:
        sources:
          - ubuntu-toolchain-r-test
        apt:
          packages:
            - g++-4.6
      env: COMPILER=g++-4.6
  include:
    - compiler: gcc
      addons:
        sources:
          - ubuntu-toolchain-r-test
        apt:
          packages:
            - g++-5
      env: COMPILER=g++-5
  include:
    - compiler: clang
      addons:
        sources:
          - ubuntu-toolchain-r-test
        apt:
          packages:
            - llvm-toolchain-precise-3.8
            - clang++-3.8
            - libiomp5
            - libiomp5-dev
      env: COMPILER=clang++-3.8
