
sudo: required

# Enable C++ support
language: cpp

# Install dependencies (Eigen3 >= 3.2.5, MatIO 1.5)
install:
  # Eigen3:
  - curl -L https://bitbucket.org/eigen/eigen/get/3.2.5.tar.gz -o eigen-3.2.5.tar.gz
  - tar xvfz eigen-3.2.5.tar.gz
  - export EIGEN_PATH=`pwd`/eigen-eigen-bdd17ee3b1b3
  # MatIO:
  - curl -L -o matio-1.5.9.tar.gz  https://sourceforge.net/projects/matio/files/matio/1.5.9/matio-1.5.9.tar.gz/download
  - tar xvfz matio-1.5.9.tar.gz
  - ( cd matio-1.5.9 && ./configure --prefix=/usr && make && sudo make install )


# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. -DTOMOGRAPHER_ENABLE_TESTS=on -DEIGEN3_INCLUDE_DIR="$EIGEN_PATH" && make VERBOSE=1 && make test

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.6
            - g++-4.6
            - libboost-all-dev
      env: COMPILER=g++-4.6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - libboost-all-dev
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang++-3.8
            - libc++
            - libboost-all-dev
      env:
        - COMPILER=clang++-3.8
        - CXXFLAGS=-stdlib=libc++

# No e-mail notifications
notifications:
  email: false
