
# more recent distro - Ubuntu Wily 15.10 (need Eigen3 >= 3.2.5)
sudo: required
dist: wily

# Enable C++ support
language: cpp

# Compiler selection
#compiler:
#  - clang
#  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. -DTOMOGRAPHER_ENABLE_TESTS=on && make VERBOSE=1 && make test


matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.6
            - g++-4.6
            - libeigen3-dev
            - libboost-all-dev
            - libmatio2
            - libmatio-dev
      env: COMPILER=g++-4.6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - libeigen3-dev
            - libboost-all-dev
            - libmatio2
            - libmatio-dev
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang++-3.9
            - libiomp5
            - libiomp-dev
            - libeigen3-dev
            - libboost-all-dev
            - libmatio2
            - libmatio-dev
      env: COMPILER=clang++-3.9
