
dist: trusty
sudo: required

# Enable C++ support
language: cpp

# Install dependencies (Eigen3 >= 3.2.5, MatIO 1.5, CMake >= 3.1)
install:
  - pwd
  # Eigen3: need >= 3.3
  - export EIGEN_PATH=`pwd`/eigen-3.3.1
  - if [ ! -f "$EIGEN_PATH/Eigen/src/Core/util/Macros.h" ]; then curl -L https://bitbucket.org/eigen/eigen/get/3.3.1.tar.gz -o eigen-3.3.1.tar.gz && tar xfz eigen-3.3.1.tar.gz && mkdir -p eigen-3.3.1 && mv eigen-eigen-f562a193118d/* eigen-3.3.1 ; fi
  # MatIO:
  - export MATIO_PATH=`pwd`/matio-1.5.9
  - if [ ! -f "$MATIO_PATH/_install/include/matio.h" ]; then curl -L -o matio-1.5.9.tar.gz  https://sourceforge.net/projects/matio/files/matio/1.5.9/matio-1.5.9.tar.gz/download  && tar xfz matio-1.5.9.tar.gz && ( cd matio-1.5.9 && ./configure --prefix="$MATIO_PATH/_install" && make && make install ) ; fi
  # CMake:
  - export CMAKE_PATH=`pwd`/cmake-3.1.3-Linux-x86_64
  - if [ ! -f "$CMAKE_PATH/bin/cmake" ]; then curl -L -O https://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz && tar xfz cmake-3.1.3-Linux-x86_64.tar.gz ; fi
  # Python dependencies -- install for both python2 and/or python3, whichever works, and use the default complier
  - (CC="gcc" /usr/bin/pip install $PIP_EXTRAS cvxpy --user ; CC="gcc" /usr/bin/pip3 install $PIP_EXTRAS cvxpy --user) || true

cache:
  pip: true
  directories:
    - eigen-3.3.1
    - matio-1.5.9/_install
    - cmake-3.1.3-Linux-x86_64


# Allow git-describe to find the right version string, otherwise the build fails
git:
  depth: 150


# Build steps
script:
  - mkdir build
  - cd build
  - $CMAKE_PATH/bin/cmake .. $CMAKE_COMPILER_ARGS -DBUILD_TOMOPY=on -DTOMOGRAPHER_ENABLE_TESTS=on -DEIGEN3_INCLUDE_DIR="$EIGEN_PATH" -DMATIO_INCLUDE_DIR="$MATIO_PATH/_install/include" -DMATIO_LIBRARY="$MATIO_PATH/_install/lib/libmatio.so"  || cat build/CMakeFiles/CMakeError.log
  - make VERBOSE=1
  - CTEST_OUTPUT_ON_FAILURE=1 BOOST_TEST_LOG_LEVEL=all $CMAKE_PATH/bin/ctest --timeout 300

matrix:
  include:
    - compiler: gcc
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.6
            - g++-4.6
            - gfortran-4.6
            - python-dev
            - python-matplotlib
            - python-tk
            - python-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost-python-dev
            - libboost-all-dev
      env:
        - CMAKE_COMPILER_ARGS="-DCMAKE_C_COMPILER=gcc-4.6 -DCMAKE_CXX_COMPILER=g++-4.6 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_EXECUTABLE=/usr/bin/python -DCMAKE_CXX11_STANDARD_COMPILE_OPTION=-std=c++0x -DCMAKE_CXX_FLAGS=-std=c++0x"
        - PIP_EXTRAS="numpy==1.9 scipy==0.16"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - gfortran-5
            - python-dev
            - python-numpy
            - python-scipy
            - python-matplotlib
            - python-tk
            - python-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost-python-dev
            - libboost-all-dev
      env:
        - CMAKE_COMPILER_ARGS="-DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_EXECUTABLE=/usr/bin/python"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
            - python3-dev
            - python3-numpy
            - python3-scipy
            - python3-matplotlib
            - python3-tk
            - python3-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost-python-dev
            - libboost-all-dev
      env:
        - CMAKE_COMPILER_ARGS="-DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 -DBoost_PYTHON_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libboost_python-py34.so -DPYTHON_EXECUTABLE=/usr/bin/python3"
    - compiler: clang
      addons:
        apt:
          packages:
            - libiomp5
            - libiomp-dev
            - python3-dev
            - python3-numpy
            - python3-scipy
            - python3-matplotlib
            - python3-tk
            - python3-pip
            - gfortran-6
            - libatlas-dev
            - libatlas-base-dev
            - libboost-python-dev
            - libboost-all-dev
      before_install:
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        - sudo apt-get update
        - sudo apt-get install clang-3.8 clang++-3.8
      env:
        - CMAKE_COMPILER_ARGS="-DCMAKE_C_COMPILER=clang-3.8 -DCMAKE_CXX_COMPILER=clang++-3.8 -DOpenMP_C_FLAGS='-fopenmp=libiomp5' -DOpenMP_CXX_FLAGS='-fopenmp=libiomp5' -DBoost_PYTHON_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libboost_python-py34.so  -DPYTHON_EXECUTABLE=/usr/bin/python3"

# No e-mail notifications
notifications:
  email: false
