
dist: trusty
sudo: required

# Enable C++ support
language: cpp

# Install dependencies (Eigen3 >= 3.2.5, MatIO 1.5)
install:
  # Eigen3:
  - curl -L https://bitbucket.org/eigen/eigen/get/3.2.5.tar.gz -o eigen-3.2.5.tar.gz
  - tar xvfz eigen-3.2.5.tar.gz
  - export EIGEN_PATH=`pwd`/eigen-eigen-bdd17ee3b1b3
  # MatIO:
  - curl -L -o matio-1.5.9.tar.gz  https://sourceforge.net/projects/matio/files/matio/1.5.9/matio-1.5.9.tar.gz/download
  - tar xvfz matio-1.5.9.tar.gz
  - ( cd matio-1.5.9 && ./configure --prefix=/usr && make && sudo make install )


# Allow git-describe to find the right version string, otherwise the build fails
git:
  depth: 100


# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. $CMAKE_COMPILER_ARGS -DTOMOGRAPHER_ENABLE_TESTS=on -DEIGEN3_INCLUDE_DIR="$EIGEN_PATH" && make VERBOSE=1 && make test

matrix:
  include:
    - compiler: gcc
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.6
            - g++-4.6
            - libboost-all-dev
      env:
        - CMAKE_COMPILER_ARGS="-DCMAKE_C_COMPILER=gcc-4.6 -DCMAKE_CXX_COMPILER=g++-4.6"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - libboost-all-dev
      env:
        - CMAKE_COMPILER_ARGS="-DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libboost-all-dev
      env:
        - CMAKE_COMPILER_ARGS="-DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6"
    - compiler: clang
      addons:
        apt:
          packages:
            - libiomp5
            - libiomp-dev
            - libboost-all-dev
      before_install:
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        - sudo apt-get update
        - sudo apt-get install clang-3.8 clang++-3.8
      env:
        - CMAKE_COMPILER_ARGS="-DCMAKE_C_COMPILER=clang-3.8 -DCMAKE_CXX_COMPILER=clang++-3.8 -DOpenMP_C_FLAGS='-fopenmp=libomp' -DOpenMP_CXX_FLAGS='-fopenmp=libomp'"

# No e-mail notifications
notifications:
  email: false
