
dist: trusty
sudo: required

# Enable C++ support
language: cpp

# Install dependencies (Eigen3 >= 3.2.5, MatIO 1.5, CMake >= 3.1)
install:
  - pwd
  # Eigen3: need >= 3.3
  - export EIGEN_PATH=`pwd`/eigen-3.3.1
  - if [ ! -f "$EIGEN_PATH/Eigen/src/Core/util/Macros.h" ]; then curl -L https://bitbucket.org/eigen/eigen/get/3.3.1.tar.gz -o eigen-3.3.1.tar.gz && tar xfz eigen-3.3.1.tar.gz && mkdir -p eigen-3.3.1 && mv eigen-eigen-f562a193118d/* eigen-3.3.1 ; fi
  # MatIO:
  - export MATIO_PATH=`pwd`/matio-1.5.9
  - if [ ! -f "$MATIO_PATH/_install/include/matio.h" ]; then curl -L -o matio-1.5.9.tar.gz  https://sourceforge.net/projects/matio/files/matio/1.5.9/matio-1.5.9.tar.gz/download  && tar xfz matio-1.5.9.tar.gz && ( cd matio-1.5.9 && ./configure --prefix="$MATIO_PATH/_install" && make && make install ) ; fi
  # CMake:
  - export CMAKE_PATH=`pwd`/cmake-3.1.3-Linux-x86_64
  - if [ ! -f "$CMAKE_PATH/bin/cmake" ]; then curl -L -O https://cmake.org/files/v3.1/cmake-3.1.3-Linux-x86_64.tar.gz && tar xfz cmake-3.1.3-Linux-x86_64.tar.gz ; fi
  # Python dependencies
  - travis_wait sh -c "CC=${PIP_CC=gcc} CXX=${PIP_CXX=g++} sudo -H $PIP install $PIP_EXTRAS cvxpy >pip_output.txt 2>&1"
  - cat pip_output.txt

cache:
  pip: true
  directories:
    - eigen-3.3.1
    - matio-1.5.9/_install
    - cmake-3.1.3-Linux-x86_64


# Allow git-describe to find the right version string, otherwise the build fails
git:
  depth: 150


# Build steps
script:
  - mkdir build
  - cd build
  - $CMAKE_PATH/bin/cmake .. -DCMAKE_C_COMPILER=$CMAKE_C_COMPILER -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER $CMAKE_COMPILER_ARGS -DBUILD_TOMOPY=on -DTOMOGRAPHER_ENABLE_TESTS=on -DEIGEN3_INCLUDE_DIR="$EIGEN_PATH" -DMATIO_INCLUDE_DIR="$MATIO_PATH/_install/include" -DMATIO_LIBRARY="$MATIO_PATH/_install/lib/libmatio.so" -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE  || cat build/CMakeFiles/CMakeError.log
  - make VERBOSE=1
  - CTEST_OUTPUT_ON_FAILURE=1 BOOST_TEST_LOG_LEVEL=all $CMAKE_PATH/bin/ctest --timeout 300
  - (cd py; CC=$CMAKE_C_COMPILER CXX=$CMAKE_CXX_COMPIELR CMAKE_CACHE_FILE=../build/CMakeCache.txt $PYTHON_EXECUTABLE setup.py build)

matrix:
  include:
    - compiler: gcc
      dist: precise
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.6
            - g++-4.6
            - gfortran
            - gfortran-multilib
            - python-dev
            - python-matplotlib
            - python-tk
            - python-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost-python-dev
            - libboost-all-dev
      env:
        - CMAKE_C_COMPILER=gcc-4.6
        - CMAKE_CXX_COMPILER=g++-4.6
        - PYTHON_EXECUTABLE=/usr/bin/python
        - CMAKE_COMPILER_ARGS="-DPYTHON_LIBRARY=/usr/lib/libpython2.7.so -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DCMAKE_CXX11_STANDARD_COMPILE_OPTION=-std=c++0x -DCMAKE_CXX_FLAGS=-std=c++0x"
        - PIP=/usr/bin/pip
        - PIP_EXTRAS="git+https://github.com/uqfoundation/multiprocess@93ac3f96eaa7f9865910f4572407e043eb2a5277  numpy==1.8 scipy==0.15 "
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - gfortran
            - gfortran-multilib
            - python-dev
            - python-numpy
            - python-scipy
            - python-matplotlib
            - python-tk
            - python-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost-python-dev
            - libboost-all-dev
      env:
        - CMAKE_C_COMPILER=gcc-5
        - CMAKE_CXX_COMPILER=g++-5
        - PYTHON_EXECUTABLE=/usr/bin/python
        - CMAKE_COMPILER_ARGS="-DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so -DPYTHON_INCLUDE_DIR=/usr/include/python2.7"
        - PIP=/usr/bin/pip
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran
            - gfortran-multilib
            - python3-dev
            - python3-numpy
            - python3-scipy
            - python3-matplotlib
            - python3-tk
            - python3-pip
            - libatlas-dev
            - libatlas-base-dev
            - libboost-python-dev
            - libboost-all-dev
      env:
        - CMAKE_C_COMPILER=gcc-6
        - CMAKE_CXX_COMPILER=g++-6
        - PYTHON_EXECUTABLE=/usr/bin/python3
        - CMAKE_COMPILER_ARGS="-DBoost_PYTHON_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libboost_python-py34.so"
        - PIP=/usr/bin/pip3
    - compiler: clang
      addons:
        apt:
          packages:
            - libiomp5
            - libiomp-dev
            - python3-dev
            - python3-numpy
            - python3-scipy
            - python3-matplotlib
            - python3-tk
            - python3-pip
            # to compile cvxpy:
            - gcc
            - g++
            - gfortran
            - gfortran-multilib
            - libatlas-dev
            - libatlas-base-dev
            - libboost-python-dev
            - libboost-all-dev
      before_install:
        - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
        - sudo apt-add-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
        - sudo apt-get update
        - sudo apt-get install clang-3.8 clang++-3.8
      env:
        - CMAKE_C_COMPILER=clang-3.8
        - CMAKE_CXX_COMPILER=clang++-3.8
        - PYTHON_EXECUTABLE=/usr/bin/python3
        - CMAKE_COMPILER_ARGS="-DOpenMP_C_FLAGS='-fopenmp=libiomp5' -DOpenMP_CXX_FLAGS='-fopenmp=libiomp5' -DBoost_PYTHON_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libboost_python-py34.so"
        - PIP_CC=/usr/bin/gcc
        - PIP_CXX=/usr/bin/g++
        - PIP=/usr/bin/pip3

# No e-mail notifications
notifications:
  email: false
