
#
# Site settings
#
title: Tomographer Project
email: phfaist@caltech.edu
description: > # this means to ignore newlines until "baseurl:"
  Tomographer Project - reliable data analysis for quantum tomography
baseurl: "/tomographer" # the subpath of your site, e.g. /blog/
url: "https://tomographer.github.io/" # the base hostname & protocol for your site
twitter_username: fkdfnlkdasfldnsajf
github_username:  Tomographer

#
# Build settings
#
markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

#
# Files not to exclude
#
include:
  # These dirs used by sphinx have an initial underscore and need to be explicitly included
  - _static
  - _sources
  - _downloads


# ------------------------------------------
# Tomographer available downloads & versions
# ------------------------------------------

tomographer_latest_version: v5.2
tomographer_apidoc_version: v5.2
tomographer_binaries:
  - version: 'v5.2'
    system: 'macosx'
    ext: '.tar.gz'
    title: 'Mac OS X Binaries (64-bit, TAR.GZ archive), OS X >= 10.6'
  - version: 'v5.2'
    system: 'linux'
    ext: '.tar.gz'
    title: "Linux Binaries (64-bit, TAR.GZ archive), statically linked"
  - version: 'v5.2'
    system: 'win-mingw32'
    ext: '.zip'
    title: "Windows Binaries (32-bit, ZIP archive)"

github_blob_baseurl: 'https://github.com/Tomographer/tomographer/blob/'
paper_url: 'http://dx.doi.org/10.1103/PhysRevLett.117.010404'
paper_ref: 'Ph. Faist and R. Renner, Phys. Rev. Lett. 117, 010404 (2016)'
paper_arxiv_url: 'http://arxiv.org/abs/1509.06763'
paper_arxiv_ref: 'arxiv:1509.06763'
