# Site settings
title: Tomographer Project
email: pfaist@phys.ethz.ch
description: > # this means to ignore newlines until "baseurl:"
  Tomographer Project - reliable data analysis for quantum tomography
baseurl: "/tomographer" # the subpath of your site, e.g. /blog/
url: "http://tomographer.github.io/" # the base hostname & protocol for your site
twitter_username: fkdfnlkdasfldnsajf
github_username:  Tomographer

# Build settings
markdown: kramdown
