
#
# Site settings
#
title: Tomographer Project
email: pfaist@phys.ethz.ch
description: > # this means to ignore newlines until "baseurl:"
  Tomographer Project - reliable data analysis for quantum tomography
baseurl: "/tomographer" # the subpath of your site, e.g. /blog/
url: "http://tomographer.github.io/" # the base hostname & protocol for your site
twitter_username: fkdfnlkdasfldnsajf
github_username:  Tomographer

#
# Build settings
#
markdown: kramdown



# ------------------------------------------
# Tomographer available downloads & versions
# ------------------------------------------

tomographer_latest_version: v1.1
tomographer_apidoc_version: v1.1
tomographer_binaries:
  - version: 'v1.1'
    system: 'macosx'
    ext: '.tar.gz'
    title: 'Mac OS X Binaries (64-bit, TAR.GZ archive), OS X >= 10.6'
  - version: 'v1.1'
    system: 'linux'
    ext: '.tar.gz'
    title: "Linux Binaries (64-bit, TAR.GZ archive), wherever they're compatible"

github_blob_baseurl: 'https://github.com/Tomographer/tomographer/blob/'
paper_url: 'http://arxiv.org/abs/1509.06763'
paper_ref: 'arxiv:1509.06763'
