var searchData=
[
  ['nano',['nano',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['nanoseconds',['nanoseconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['naturalordering',['NaturalOrdering',['http://eigen.tuxfamily.org/dox/classEigen_1_1NaturalOrdering.html',1,'Eigen']]],
  ['needeigenalignedoperatornew',['NeedEigenAlignedOperatorNew',['../struct_tomographer_1_1_tools_1_1_need_eigen_aligned_operator_new.html',1,'Tomographer::Tools']]],
  ['needeigenalignedoperatornew_3c_20false_20_3e',['NeedEigenAlignedOperatorNew&lt; false &gt;',['../struct_tomographer_1_1_tools_1_1_need_eigen_aligned_operator_new_3_01false_01_4.html',1,'Tomographer::Tools']]],
  ['needeigenalignedoperatornew_3c_21_28maxrows_3d_3deigen_3a_3adynamic_7c_7cmaxcols_3d_3deigen_3a_3adynamic_29_3e',['NeedEigenAlignedOperatorNew&lt;!(MaxRows==Eigen::Dynamic||MaxCols==Eigen::Dynamic)&gt;',['../struct_tomographer_1_1_tools_1_1_need_eigen_aligned_operator_new.html',1,'Tomographer::Tools']]],
  ['needownoperatornew',['NeedOwnOperatorNew',['../struct_tomographer_1_1_tools_1_1_need_own_operator_new.html',1,'Tomographer::Tools']]],
  ['needownoperatornew_3c_20eigen_3a_3aarray_3c_20scalar_2c_20fixedrows_2c_20fixedcols_2c_20options_2c_20maxrows_2c_20maxcols_20_3e_20_3e',['NeedOwnOperatorNew&lt; Eigen::Array&lt; Scalar, FixedRows, FixedCols, Options, MaxRows, MaxCols &gt; &gt;',['../struct_tomographer_1_1_tools_1_1_need_own_operator_new_3_01_eigen_1_1_array_3_01_scalar_00_01_fi27964185ced34fb5bd18fb7694a848ef.html',1,'Tomographer::Tools']]],
  ['needownoperatornew_3c_20eigen_3a_3amatrix_3c_20scalar_2c_20fixedrows_2c_20fixedcols_2c_20options_2c_20maxrows_2c_20maxcols_20_3e_20_3e',['NeedOwnOperatorNew&lt; Eigen::Matrix&lt; Scalar, FixedRows, FixedCols, Options, MaxRows, MaxCols &gt; &gt;',['../struct_tomographer_1_1_tools_1_1_need_own_operator_new_3_01_eigen_1_1_matrix_3_01_scalar_00_01_f562600b42153070dc34daa2aedab201e.html',1,'Tomographer::Tools']]],
  ['needownoperatornew_3c_20t_20_3e',['NeedOwnOperatorNew&lt; T &gt;',['../struct_tomographer_1_1_tools_1_1_need_own_operator_new_3_01_t_01_4.html',1,'Tomographer::Tools']]],
  ['needownoperatornew_3c_20type1_2c_20type2_2c_20othertypes_2e_2e_2e_20_3e',['NeedOwnOperatorNew&lt; Type1, Type2, OtherTypes... &gt;',['../struct_tomographer_1_1_tools_1_1_need_own_operator_new_3_01_type1_00_01_type2_00_01_other_types_8_8_8_01_4.html',1,'Tomographer::Tools']]],
  ['negate',['negate',['http://en.cppreference.com/w/cpp/utility/functional/negate.html',1,'std']]],
  ['negative_5fbinomial_5fdistribution',['negative_binomial_distribution',['http://en.cppreference.com/w/cpp/numeric/random/negative_binomial_distribution.html',1,'std']]],
  ['nestbyvalue',['NestByValue',['http://eigen.tuxfamily.org/dox/classEigen_1_1NestByValue.html',1,'Eigen']]],
  ['nested_5fexception',['nested_exception',['http://en.cppreference.com/w/cpp/error/nested_exception.html',1,'std']]],
  ['new_5fhandler',['new_handler',['http://en.cppreference.com/w/cpp/memory/new/new_handler.html',1,'std']]],
  ['noalias',['NoAlias',['http://eigen.tuxfamily.org/dox/classEigen_1_1NoAlias.html',1,'Eigen']]],
  ['normal_5fdistribution',['normal_distribution',['http://en.cppreference.com/w/cpp/numeric/random/normal_distribution.html',1,'std']]],
  ['normal_5fdistribution_3c_20realscalar_20_3e',['normal_distribution&lt; RealScalar &gt;',['http://en.cppreference.com/w/cpp/numeric/random/normal_distribution.html',1,'std']]],
  ['nospecialoperatornew',['NoSpecialOperatorNew',['../struct_tomographer_1_1_tools_1_1_no_special_operator_new.html',1,'Tomographer::Tools']]],
  ['nospecialoperatornewprovider',['NoSpecialOperatorNewProvider',['../struct_tomographer_1_1_tools_1_1_no_special_operator_new_provider.html',1,'Tomographer::Tools']]],
  ['not_5fequal_5fto',['not_equal_to',['http://en.cppreference.com/w/cpp/utility/functional/not_equal_to.html',1,'std']]],
  ['nothrow_5ft',['nothrow_t',['http://en.cppreference.com/w/cpp/memory/new/nothrow_t.html',1,'std']]],
  ['nullptr_5ft',['nullptr_t',['http://en.cppreference.com/w/cpp/types/nullptr_t.html',1,'std']]],
  ['num_5fget',['num_get',['http://en.cppreference.com/w/cpp/locale/num_get.html',1,'std']]],
  ['num_5fput',['num_put',['http://en.cppreference.com/w/cpp/locale/num_put.html',1,'std']]],
  ['numeric_5flimits',['numeric_limits',['http://en.cppreference.com/w/cpp/types/numeric_limits.html',1,'std']]],
  ['numpunct',['numpunct',['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std']]],
  ['numpunct_5fbyname',['numpunct_byname',['http://en.cppreference.com/w/cpp/locale/numpunct_byname.html',1,'std']]],
  ['numtraits',['NumTraits',['http://eigen.tuxfamily.org/dox/structEigen_1_1NumTraits.html',1,'Eigen']]]
];
