var multiprocthreadcommon_8h =
[
    [ "TaskDispatcherBase", "class_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base.html", "class_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base" ],
    [ "TaskInterruptedInnerException", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_task_interrupted_inner_exception.html", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_task_interrupted_inner_exception" ],
    [ "ThreadSharedData", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_thread_shared_data.html", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_thread_shared_data" ],
    [ "Schedule", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_thread_shared_data_1_1_schedule.html", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_thread_shared_data_1_1_schedule" ],
    [ "StatusReport", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_thread_shared_data_1_1_status_report.html", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_thread_shared_data_1_1_status_report" ],
    [ "ThreadPrivateData", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_thread_private_data.html", "struct_tomographer_1_1_multi_proc_1_1_thread_common_1_1_task_dispatcher_base_1_1_thread_private_data" ],
    [ "TOMOGRAPHER_SLEEP_FOR_MS", "multiprocthreadcommon_8h.html#a03e132b001cd20f46bb6a680d608ce62", null ]
];