var namespace_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tools =
[
    [ "CDataBase", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tools_1_1_c_data_base.html", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tools_1_1_c_data_base" ],
    [ "MHRWStatsResultsBaseSimple", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tools_1_1_m_h_r_w_stats_results_base_simple.html", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tools_1_1_m_h_r_w_stats_results_base_simple" ]
];