var namespace_tomographer_1_1_logger =
[
    [ "BoostTestLogger", "class_tomographer_1_1_logger_1_1_boost_test_logger.html", "class_tomographer_1_1_logger_1_1_boost_test_logger" ],
    [ "BufferLogger", "class_tomographer_1_1_logger_1_1_buffer_logger.html", "class_tomographer_1_1_logger_1_1_buffer_logger" ],
    [ "DefaultLoggerTraits", "struct_tomographer_1_1_logger_1_1_default_logger_traits.html", "struct_tomographer_1_1_logger_1_1_default_logger_traits" ],
    [ "FileLogger", "class_tomographer_1_1_logger_1_1_file_logger.html", "class_tomographer_1_1_logger_1_1_file_logger" ],
    [ "LocalLogger", "class_tomographer_1_1_logger_1_1_local_logger.html", "class_tomographer_1_1_logger_1_1_local_logger" ],
    [ "LocalLoggerOriginSpec", "struct_tomographer_1_1_logger_1_1_local_logger_origin_spec.html", "struct_tomographer_1_1_logger_1_1_local_logger_origin_spec" ],
    [ "LoggerBase", "class_tomographer_1_1_logger_1_1_logger_base.html", "class_tomographer_1_1_logger_1_1_logger_base" ],
    [ "LoggerTraits", "struct_tomographer_1_1_logger_1_1_logger_traits.html", null ],
    [ "LoggerTraits< BoostTestLogger >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_boost_test_logger_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_boost_test_logger_01_4" ],
    [ "LoggerTraits< BufferLogger >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_buffer_logger_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_buffer_logger_01_4" ],
    [ "LoggerTraits< FileLogger >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_file_logger_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_file_logger_01_4" ],
    [ "LoggerTraits< LocalLogger< BaseLoggerType_ > >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_local_logger_3_01_base_logger_type___01_4_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_local_logger_3_01_base_logger_type___01_4_01_4" ],
    [ "LoggerTraits< MinimumSeverityLogger< BaseLogger, Level > >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_minimum_severity_logger_3_01_base_logger_00_01_level_01_4_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_minimum_severity_logger_3_01_base_logger_00_01_level_01_4_01_4" ],
    [ "LoggerTraits< MultiProc::CxxThreads::ThreadSanitizerLogger< BaseLogger > >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_multi_proc_1_1_cxx_threads_1_1_thread_sanitb4e4ff0abba6a39822cce1c99e885e9a.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_multi_proc_1_1_cxx_threads_1_1_thread_sanitb4e4ff0abba6a39822cce1c99e885e9a" ],
    [ "LoggerTraits< MultiProc::OMP::ThreadSanitizerLogger< BaseLogger > >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_multi_proc_1_1_o_m_p_1_1_thread_sanitizer_l7f0064bd162e246a0e99630591611d67.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_multi_proc_1_1_o_m_p_1_1_thread_sanitizer_l7f0064bd162e246a0e99630591611d67" ],
    [ "LoggerTraits< OriginFilteredLogger< BaseLogger > >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_origin_filtered_logger_3_01_base_logger_01_4_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_origin_filtered_logger_3_01_base_logger_01_4_01_4" ],
    [ "LoggerTraits< OriginPrefixedLogger< BaseLogger > >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_origin_prefixed_logger_3_01_base_logger_01_4_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_origin_prefixed_logger_3_01_base_logger_01_4_01_4" ],
    [ "LoggerTraits< tpy::GilProtectedPyLogger >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01tpy_1_1_gil_protected_py_logger_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01tpy_1_1_gil_protected_py_logger_01_4" ],
    [ "LoggerTraits< tpy::PyLogger >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01tpy_1_1_py_logger_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01tpy_1_1_py_logger_01_4" ],
    [ "LoggerTraits< VacuumLogger >", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_vacuum_logger_01_4.html", "struct_tomographer_1_1_logger_1_1_logger_traits_3_01_vacuum_logger_01_4" ],
    [ "LogLevel", "class_tomographer_1_1_logger_1_1_log_level.html", "class_tomographer_1_1_logger_1_1_log_level" ],
    [ "MinimumSeverityLogger", "class_tomographer_1_1_logger_1_1_minimum_severity_logger.html", "class_tomographer_1_1_logger_1_1_minimum_severity_logger" ],
    [ "OriginFilteredLogger", "class_tomographer_1_1_logger_1_1_origin_filtered_logger.html", "class_tomographer_1_1_logger_1_1_origin_filtered_logger" ],
    [ "OriginPrefixedLogger", "class_tomographer_1_1_logger_1_1_origin_prefixed_logger.html", "class_tomographer_1_1_logger_1_1_origin_prefixed_logger" ],
    [ "StaticIsAtLeastOfSeverity", "struct_tomographer_1_1_logger_1_1_static_is_at_least_of_severity.html", "struct_tomographer_1_1_logger_1_1_static_is_at_least_of_severity" ],
    [ "VacuumLogger", "class_tomographer_1_1_logger_1_1_vacuum_logger.html", "class_tomographer_1_1_logger_1_1_vacuum_logger" ]
];