var namespace_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tasks =
[
    [ "CDataBase", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tasks_1_1_c_data_base.html", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tasks_1_1_c_data_base" ],
    [ "ResultsCollectorSimple", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tasks_1_1_results_collector_simple.html", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tasks_1_1_results_collector_simple" ],
    [ "ResultsCollectorWithBinningAnalysis", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tasks_1_1_results_collector_with_binning_analysis.html", "struct_tomographer_1_1_m_h_r_w_tasks_1_1_value_histogram_tasks_1_1_results_collector_with_binning_analysis" ]
];