var searchData=
[
  ['has_5fvirtual_5fdestructor',['has_virtual_destructor',['http://en.cppreference.com/w/cpp/types/has_virtual_destructor.html',1,'std']]],
  ['hash',['hash',['http://en.cppreference.com/w/cpp/utility/hash.html',1,'std']]],
  ['hasostreamop',['hasOStreamOp',['../struct_tomographer_1_1_tools_1_1has_o_stream_op.html',1,'Tomographer::Tools']]],
  ['hecto',['hecto',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['hessenbergdecomposition',['HessenbergDecomposition',['http://eigen.tuxfamily.org/dox/classEigen_1_1HessenbergDecomposition.html',1,'Eigen']]],
  ['high_5fresolution_5fclock',['high_resolution_clock',['http://en.cppreference.com/w/cpp/chrono/high_resolution_clock.html',1,'std::chrono']]],
  ['histogram',['Histogram',['../class_tomographer_1_1_histogram.html',1,'Tomographer']]],
  ['histogram',['Histogram',['../structtpy_1_1_histogram.html',1,'tpy']]],
  ['histogram_3c_20histogramtype_20_3a_3ascalar_2c_20countrealtype_20_3e',['Histogram&lt; HistogramType ::Scalar, CountRealType &gt;',['../class_tomographer_1_1_histogram.html',1,'Tomographer']]],
  ['histogram_3c_20histogramtype_5f_3a_3ascalar_2c_20realavgtype_20_3e',['Histogram&lt; HistogramType_::Scalar, RealAvgType &gt;',['../class_tomographer_1_1_histogram.html',1,'Tomographer']]],
  ['histogram_3c_20simplehistogramtype_20_3a_3ascalar_2c_20countrealtype_20_3e',['Histogram&lt; SimpleHistogramType ::Scalar, CountRealType &gt;',['../class_tomographer_1_1_histogram.html',1,'Tomographer']]],
  ['histogramparams',['HistogramParams',['../struct_tomographer_1_1_histogram_params.html',1,'Tomographer']]],
  ['histogramparams_3c_20histogramtype_20_3a_3ascalar_20_3e',['HistogramParams&lt; HistogramType ::Scalar &gt;',['../struct_tomographer_1_1_histogram_params.html',1,'Tomographer']]],
  ['histogramparams_3c_20histogramtype_5f_3a_3ascalar_20_3e',['HistogramParams&lt; HistogramType_::Scalar &gt;',['../struct_tomographer_1_1_histogram_params.html',1,'Tomographer']]],
  ['histogramparams_3c_20realtype_20_3e',['HistogramParams&lt; RealType &gt;',['../struct_tomographer_1_1_histogram_params.html',1,'Tomographer']]],
  ['histogramparams_3c_20simplehistogramtype_20_3a_3ascalar_20_3e',['HistogramParams&lt; SimpleHistogramType ::Scalar &gt;',['../struct_tomographer_1_1_histogram_params.html',1,'Tomographer']]],
  ['histogramwitherrorbars',['HistogramWithErrorBars',['../structtpy_1_1_histogram_with_error_bars.html',1,'tpy']]],
  ['histogramwitherrorbars',['HistogramWithErrorBars',['../class_tomographer_1_1_histogram_with_error_bars.html',1,'Tomographer']]],
  ['histogramwitherrorbars_3c_20histogramtype_20_3a_3ascalar_2c_20countrealtype_20_3e',['HistogramWithErrorBars&lt; HistogramType ::Scalar, CountRealType &gt;',['../class_tomographer_1_1_histogram_with_error_bars.html',1,'Tomographer']]],
  ['histogramwitherrorbars_3c_20histogramtype_5f_3a_3ascalar_2c_20realavgtype_20_3e',['HistogramWithErrorBars&lt; HistogramType_::Scalar, RealAvgType &gt;',['../class_tomographer_1_1_histogram_with_error_bars.html',1,'Tomographer']]],
  ['histogramwitherrorbars_3c_20simplehistogramtype_20_3a_3ascalar_2c_20countrealtype_20_3e',['HistogramWithErrorBars&lt; SimpleHistogramType ::Scalar, CountRealType &gt;',['../class_tomographer_1_1_histogram_with_error_bars.html',1,'Tomographer']]],
  ['homogeneous',['Homogeneous',['http://eigen.tuxfamily.org/dox/classEigen_1_1Homogeneous.html',1,'Eigen']]],
  ['hours',['hours',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['householderqr',['HouseholderQR',['http://eigen.tuxfamily.org/dox/classEigen_1_1HouseholderQR.html',1,'Eigen']]],
  ['householdersequence',['HouseholderSequence',['http://eigen.tuxfamily.org/dox/classEigen_1_1HouseholderSequence.html',1,'Eigen']]],
  ['hyperplane',['Hyperplane',['http://eigen.tuxfamily.org/dox/classEigen_1_1Hyperplane.html',1,'Eigen']]]
];
