var searchData=
[
  ['packaged_5ftask',['packaged_task',['http://en.cppreference.com/w/cpp/thread/packaged_task.html',1,'std']]],
  ['pair',['pair',['http://en.cppreference.com/w/cpp/utility/pair.html',1,'std']]],
  ['parametrizedline',['ParametrizedLine',['http://eigen.tuxfamily.org/dox/classEigen_1_1ParametrizedLine.html',1,'Eigen']]],
  ['paramrhoa',['ParamRhoA',['../class_tomographer_1_1_param_rho_a.html',1,'Tomographer']]],
  ['params',['Params',['../struct_tomographer_1_1_uniform_bins_histogram_1_1_params.html',1,'Tomographer::UniformBinsHistogram']]],
  ['pardisoldlt',['PardisoLDLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1PardisoLDLT.html',1,'Eigen']]],
  ['pardisollt',['PardisoLLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1PardisoLLT.html',1,'Eigen']]],
  ['pardisolu',['PardisoLU',['http://eigen.tuxfamily.org/dox/classEigen_1_1PardisoLU.html',1,'Eigen']]],
  ['partialpivlu',['PartialPivLU',['http://eigen.tuxfamily.org/dox/classEigen_1_1PartialPivLU.html',1,'Eigen']]],
  ['partialreduxexpr',['PartialReduxExpr',['http://eigen.tuxfamily.org/dox/classEigen_1_1PartialReduxExpr.html',1,'Eigen']]],
  ['pastixldlt',['PastixLDLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1PastixLDLT.html',1,'Eigen']]],
  ['pastixllt',['PastixLLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1PastixLLT.html',1,'Eigen']]],
  ['pastixlu',['PastixLU',['http://eigen.tuxfamily.org/dox/classEigen_1_1PastixLU.html',1,'Eigen']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::money_put']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::moneypunct_byname']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::money_base']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::money_get']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::moneypunct']]],
  ['permutationbase',['PermutationBase',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationBase.html',1,'Eigen']]],
  ['permutationbase_3c_20permutationmatrix_3c_20sizeatcompiletime_2c_20maxsizeatcompiletime_2c_20indextype_20_3e_20_3e',['PermutationBase&lt; PermutationMatrix&lt; SizeAtCompileTime, MaxSizeAtCompileTime, IndexType &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationBase.html',1,'Eigen']]],
  ['permutationbase_3c_20permutationwrapper_3c_20_5findicestype_20_3e_20_3e',['PermutationBase&lt; PermutationWrapper&lt; _IndicesType &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationBase.html',1,'Eigen']]],
  ['permutationmatrix',['PermutationMatrix',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationMatrix.html',1,'Eigen']]],
  ['permutationwrapper',['PermutationWrapper',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationWrapper.html',1,'Eigen']]],
  ['peta',['peta',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['pico',['pico',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['piecewise_5fconstant_5fdistribution',['piecewise_constant_distribution',['http://en.cppreference.com/w/cpp/numeric/random/piecewise_constant_distribution.html',1,'std']]],
  ['piecewise_5fconstruct_5ft',['piecewise_construct_t',['http://en.cppreference.com/w/cpp/utility/piecewise_construct_t.html',1,'std']]],
  ['piecewise_5flinear_5fdistribution',['piecewise_linear_distribution',['http://en.cppreference.com/w/cpp/numeric/random/piecewise_linear_distribution.html',1,'std']]],
  ['placeholders',['placeholders',['http://en.cppreference.com/w/cpp/utility/functional/placeholders.html',1,'std']]],
  ['plainobjectbase',['PlainObjectBase',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plainobjectbase_3c_20array_3c_20_5fscalar_2c_20_5frows_2c_20_5fcols_2c_20_5foptions_2c_20_5fmaxrows_2c_20_5fmaxcols_20_3e_20_3e',['PlainObjectBase&lt; Array&lt; _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plainobjectbase_3c_20array_3c_20counttype_2c_20eigen_3a_3adynamic_2c_201_2c_20_5foptions_2c_20_5fmaxrows_2c_20_5fmaxcols_20_3e_20_3e',['PlainObjectBase&lt; Array&lt; CountType, Eigen::Dynamic, 1, _Options, _MaxRows, _MaxCols &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plainobjectbase_3c_20matrix_3c_20_5fscalar_2c_20_5frows_2c_20_5fcols_2c_20_5foptions_2c_20_5fmaxrows_2c_20_5fmaxcols_20_3e_20_3e',['PlainObjectBase&lt; Matrix&lt; _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plus',['plus',['http://en.cppreference.com/w/cpp/utility/functional/plus.html',1,'std']]],
  ['pointer_5fsafety',['pointer_safety',['http://en.cppreference.com/w/cpp/memory/gc/pointer_safety.html',1,'std']]],
  ['pointer_5ftraits',['pointer_traits',['http://en.cppreference.com/w/cpp/memory/pointer_traits.html',1,'std']]],
  ['poisson_5fdistribution',['poisson_distribution',['http://en.cppreference.com/w/cpp/numeric/random/poisson_distribution.html',1,'std']]],
  ['priority_5fqueue',['priority_queue',['http://en.cppreference.com/w/cpp/container/priority_queue.html',1,'std']]],
  ['productreturntype',['ProductReturnType',['http://eigen.tuxfamily.org/dox/structEigen_1_1ProductReturnType.html',1,'Eigen']]],
  ['promise',['promise',['http://en.cppreference.com/w/cpp/thread/promise.html',1,'std']]],
  ['ptrdiff_5ft',['ptrdiff_t',['http://en.cppreference.com/w/cpp/types/ptrdiff_t.html',1,'std']]],
  ['purifdisttorefcalculator',['PurifDistToRefCalculator',['../class_tomographer_1_1_purif_dist_to_ref_calculator.html',1,'Tomographer']]]
];
