var searchData=
[
  ['scaling',['Scaling',['http://eigen.tuxfamily.org/dox/classScaling.html',1,'']]],
  ['schedule',['Schedule',['../struct_tomographer_1_1_multi_proc_1_1_cxx_threads_1_1_task_dispatcher_1_1thread__shared__data_1_1_schedule.html',1,'Tomographer::MultiProc::CxxThreads::TaskDispatcher::thread_shared_data']]],
  ['scoped_5fallocator_5fadaptor',['scoped_allocator_adaptor',['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor.html',1,'std']]],
  ['seconds',['seconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['seed_5fseq',['seed_seq',['http://en.cppreference.com/w/cpp/numeric/random/seed_seq.html',1,'std']]],
  ['select',['Select',['http://eigen.tuxfamily.org/dox/classEigen_1_1Select.html',1,'Eigen']]],
  ['selfadjointeigensolver',['SelfAdjointEigenSolver',['http://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointEigenSolver.html',1,'Eigen']]],
  ['selfadjointeigensolver_3c_20eigentype_20_3e',['SelfAdjointEigenSolver&lt; EigenType &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointEigenSolver.html',1,'Eigen']]],
  ['selfadjointview',['SelfAdjointView',['http://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointView.html',1,'Eigen']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_fstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::iostream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istrstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wstringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::strstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ofstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wiostream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wostringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::fstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_istringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::basic_ifstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::stringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ostringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::istringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wistringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::ifstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostrstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wfstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_stringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'std::wifstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_iostream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::ostringstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::wofstream']]],
  ['sentry',['sentry',['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'std::basic_ofstream']]],
  ['set',['set',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['shared_5ffuture',['shared_future',['http://en.cppreference.com/w/cpp/thread/shared_future.html',1,'std']]],
  ['shared_5flock',['shared_lock',['http://en.cppreference.com/w/cpp/thread/shared_lock.html',1,'std']]],
  ['shared_5fptr',['shared_ptr',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5ftimed_5fmutex',['shared_timed_mutex',['http://en.cppreference.com/w/cpp/thread/shared_timed_mutex.html',1,'std']]],
  ['shuffle_5forder_5fengine',['shuffle_order_engine',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std']]],
  ['sig_5fatomic_5ft',['sig_atomic_t',['http://en.cppreference.com/w/cpp/utility/program/sig_atomic_t.html',1,'std']]],
  ['sighandlertaskdispatcherstatusreporter',['SigHandlerTaskDispatcherStatusReporter',['../struct_tomographer_1_1_tools_1_1_sig_handler_task_dispatcher_status_reporter.html',1,'Tomographer::Tools']]],
  ['signalhandler',['SignalHandler',['../struct_tomographer_1_1_tools_1_1_signal_handler.html',1,'Tomographer::Tools']]],
  ['simplicialcholesky',['SimplicialCholesky',['http://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialCholesky.html',1,'Eigen']]],
  ['simplicialcholeskybase',['SimplicialCholeskyBase',['http://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialcholesky_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialCholesky&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialldlt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialLDLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialcholeskybase_3c_20simplicialllt_3c_20_5fmatrixtype_2c_20_5fuplo_2c_20_5fordering_20_3e_20_3e',['SimplicialCholeskyBase&lt; SimplicialLLT&lt; _MatrixType, _UpLo, _Ordering &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialCholeskyBase.html',1,'Eigen']]],
  ['simplicialldlt',['SimplicialLDLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialLDLT.html',1,'Eigen']]],
  ['simplicialllt',['SimplicialLLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1SimplicialLLT.html',1,'Eigen']]],
  ['size_5ft',['size_t',['http://en.cppreference.com/w/cpp/types/size_t.html',1,'std']]],
  ['smatch',['smatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['solveerror',['SolveError',['../class_tomographer_1_1_math_tools_1_1_solve_c_lyap_1_1_solve_error.html',1,'Tomographer::MathTools::SolveCLyap']]],
  ['sparse',['Sparse',['http://eigen.tuxfamily.org/dox/structEigen_1_1Sparse.html',1,'Eigen']]],
  ['sparselu',['SparseLU',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseLU.html',1,'Eigen']]],
  ['sparsematrix',['SparseMatrix',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html',1,'Eigen']]],
  ['sparsematrixbase',['SparseMatrixBase',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_20_3e',['SparseMatrixBase&lt; Block&lt; XprType, BlockRows, BlockCols, InnerPanel &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20mappedsparsematrix_3c_20_5fscalar_2c_20_5fflags_2c_20_5findex_20_3e_20_3e',['SparseMatrixBase&lt; MappedSparseMatrix&lt; _Scalar, _Flags, _Index &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparsematrix_3c_20_5fscalar_2c_20_5foptions_2c_20_5findex_20_3e_20_3e',['SparseMatrixBase&lt; SparseMatrix&lt; _Scalar, _Options, _Index &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparsematrixbase_3c_20sparsevector_3c_20_5fscalar_2c_20_5foptions_2c_20_5findex_20_3e_20_3e',['SparseMatrixBase&lt; SparseVector&lt; _Scalar, _Options, _Index &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrixBase.html',1,'Eigen']]],
  ['sparseqr',['SparseQR',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseQR.html',1,'Eigen']]],
  ['sparseselfadjointview',['SparseSelfAdjointView',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseSelfAdjointView.html',1,'Eigen']]],
  ['sparsevector',['SparseVector',['http://eigen.tuxfamily.org/dox/classEigen_1_1SparseVector.html',1,'Eigen']]],
  ['spqr',['SPQR',['http://eigen.tuxfamily.org/dox/classEigen_1_1SPQR.html',1,'Eigen']]],
  ['sregex_5fiterator',['sregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['sregex_5ftoken_5fiterator',['sregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['ssub_5fmatch',['ssub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['stack',['stack',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['state_5ftype',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8_utf16']]],
  ['state_5ftype',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt']]],
  ['state_5ftype',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_byname']]],
  ['state_5ftype',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf8']]],
  ['state_5ftype',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'std::codecvt_utf16']]],
  ['staticisatleastofseverity',['StaticIsAtLeastOfSeverity',['../struct_tomographer_1_1_logger_1_1_static_is_at_least_of_severity.html',1,'Tomographer::Logger']]],
  ['staticordynamic',['StaticOrDynamic',['../class_tomographer_1_1_tools_1_1_static_or_dynamic.html',1,'Tomographer::Tools']]],
  ['staticordynamic_3c_20countinttype_2c_28samplessizectime_3d_3deigen_3a_3adynamic_29_2c_20samplessizectime_20_3e',['StaticOrDynamic&lt; CountIntType,(SamplesSizeCTime==Eigen::Dynamic), SamplesSizeCTime &gt;',['../class_tomographer_1_1_tools_1_1_static_or_dynamic.html',1,'Tomographer::Tools']]],
  ['staticordynamic_3c_20int_2c_28numlevelsctime_3d_3deigen_3a_3adynamic_29_2c_20numlevelsctime_20_3e',['StaticOrDynamic&lt; int,(NumLevelsCTime==Eigen::Dynamic), NumLevelsCTime &gt;',['../class_tomographer_1_1_tools_1_1_static_or_dynamic.html',1,'Tomographer::Tools']]],
  ['staticordynamic_3c_20int_2c_28numtrackvaluesctime_3d_3deigen_3a_3adynamic_29_2c_20numtrackvaluesctime_20_3e',['StaticOrDynamic&lt; int,(NumTrackValuesCTime==Eigen::Dynamic), NumTrackValuesCTime &gt;',['../class_tomographer_1_1_tools_1_1_static_or_dynamic.html',1,'Tomographer::Tools']]],
  ['staticordynamic_3c_20std_3a_3asize_5ft_2c_20isdynamicdim_2c_28std_3a_3asize_5ft_29_20fixeddim_20_3e',['StaticOrDynamic&lt; std::size_t, IsDynamicDim,(std::size_t) FixedDim &gt;',['../class_tomographer_1_1_tools_1_1_static_or_dynamic.html',1,'Tomographer::Tools']]],
  ['staticordynamic_3c_20t_5f_2c_20true_2c_20staticvalue_5f_20_3e',['StaticOrDynamic&lt; T_, true, StaticValue_ &gt;',['../class_tomographer_1_1_tools_1_1_static_or_dynamic_3_01_t___00_01true_00_01_static_value___01_4.html',1,'Tomographer::Tools']]],
  ['statusreport',['StatusReport',['../struct_tomographer_1_1_m_h_r_w_tasks_1_1_m_h_random_walk_task_1_1_status_report.html',1,'Tomographer::MHRWTasks::MHRandomWalkTask']]],
  ['statusreport',['StatusReport',['../struct_tomographer_1_1_multi_proc_1_1_cxx_threads_1_1_task_dispatcher_1_1thread__shared__data_1_1_status_report.html',1,'Tomographer::MultiProc::CxxThreads::TaskDispatcher::thread_shared_data']]],
  ['steady_5fclock',['steady_clock',['http://en.cppreference.com/w/cpp/chrono/steady_clock.html',1,'std::chrono']]],
  ['storeifenabled',['StoreIfEnabled',['../struct_tomographer_1_1_tools_1_1_store_if_enabled.html',1,'Tomographer::Tools']]],
  ['storeifenabled_3c_20binsumarray_2c_20storebinsums_20_3e',['StoreIfEnabled&lt; BinSumArray, StoreBinSums &gt;',['../struct_tomographer_1_1_tools_1_1_store_if_enabled.html',1,'Tomographer::Tools']]],
  ['storeifenabled_3c_20int_2c_20usebinninganalysis_20_3e',['StoreIfEnabled&lt; int, UseBinningAnalysis &gt;',['../struct_tomographer_1_1_tools_1_1_store_if_enabled.html',1,'Tomographer::Tools']]],
  ['storeifenabled_3c_20llhvaluetype_2c_20usenmeasamplifyfactor_20_3e',['StoreIfEnabled&lt; LLHValueType, UseNMeasAmplifyFactor &gt;',['../struct_tomographer_1_1_tools_1_1_store_if_enabled.html',1,'Tomographer::Tools']]],
  ['storeifenabled_3c_20t_5f_2c_20true_20_3e',['StoreIfEnabled&lt; T_, true &gt;',['../struct_tomographer_1_1_tools_1_1_store_if_enabled_3_01_t___00_01true_01_4.html',1,'Tomographer::Tools']]],
  ['streambuf',['streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['streamoff',['streamoff',['http://en.cppreference.com/w/cpp/io/streamoff.html',1,'std']]],
  ['streampos',['streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['streamsize',['streamsize',['http://en.cppreference.com/w/cpp/io/streamsize.html',1,'std']]],
  ['stride',['Stride',['http://eigen.tuxfamily.org/dox/classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_200_2c_20value_20_3e',['Stride&lt; 0, Value &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1Stride.html',1,'Eigen']]],
  ['stride_3c_20value_2c_200_20_3e',['Stride&lt; Value, 0 &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1Stride.html',1,'Eigen']]],
  ['string',['string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'std::money_put']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/collate.html',1,'std::collate_byname']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct_byname']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'std::money_get']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'std::moneypunct_byname']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std::numpunct']]],
  ['string_5ftype',['string_type',['http://en.cppreference.com/w/cpp/locale/messages.html',1,'std::messages_byname']]],
  ['stringbuf',['stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['stringstream',['stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['strstream',['strstream',['http://en.cppreference.com/w/cpp/io/strstream.html',1,'std']]],
  ['strstreambuf',['strstreambuf',['http://en.cppreference.com/w/cpp/io/strstreambuf.html',1,'std']]],
  ['student_5ft_5fdistribution',['student_t_distribution',['http://en.cppreference.com/w/cpp/numeric/random/student_t_distribution.html',1,'std']]],
  ['sub_5fmatch',['sub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['subtract_5fwith_5fcarry_5fengine',['subtract_with_carry_engine',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['superilu',['SuperILU',['http://eigen.tuxfamily.org/dox/classEigen_1_1SuperILU.html',1,'Eigen']]],
  ['superlu',['SuperLU',['http://eigen.tuxfamily.org/dox/classEigen_1_1SuperLU.html',1,'Eigen']]],
  ['superlubase',['SuperLUBase',['http://eigen.tuxfamily.org/dox/classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['superlubase_3c_20_5fmatrixtype_2c_20superilu_3c_20_5fmatrixtype_20_3e_20_3e',['SuperLUBase&lt; _MatrixType, SuperILU&lt; _MatrixType &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['superlubase_3c_20_5fmatrixtype_2c_20superlu_3c_20_5fmatrixtype_20_3e_20_3e',['SuperLUBase&lt; _MatrixType, SuperLU&lt; _MatrixType &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1SuperLUBase.html',1,'Eigen']]],
  ['system_5fclock',['system_clock',['http://en.cppreference.com/w/cpp/chrono/system_clock.html',1,'std::chrono']]],
  ['system_5ferror',['system_error',['http://en.cppreference.com/w/cpp/error/system_error.html',1,'std']]]
];
