var searchData=
[
  ['packaged_5ftask',['packaged_task',['http://en.cppreference.com/w/cpp/thread/packaged_task.html',1,'std']]],
  ['pair',['pair',['http://en.cppreference.com/w/cpp/utility/pair.html',1,'std']]],
  ['parama',['ParamA',['../class_tomographer_1_1_dense_d_m_1_1_param_a.html',1,'Tomographer::DenseDM']]],
  ['parametrizedline',['ParametrizedLine',['http://eigen.tuxfamily.org/dox/classEigen_1_1ParametrizedLine.html',1,'Eigen']]],
  ['params',['Params',['../struct_tomographer_1_1_m_a_t_1_1_eigen_pos_semidef_matrix_with_sqrt_1_1_params.html',1,'Tomographer::MAT::EigenPosSemidefMatrixWithSqrt']]],
  ['paramx',['ParamX',['../class_tomographer_1_1_dense_d_m_1_1_param_x.html',1,'Tomographer::DenseDM']]],
  ['paramx_3c_20dmtypes_20_3e',['ParamX&lt; DMTypes &gt;',['../class_tomographer_1_1_dense_d_m_1_1_param_x.html',1,'Tomographer::DenseDM']]],
  ['pardisoldlt',['PardisoLDLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1PardisoLDLT.html',1,'Eigen']]],
  ['pardisollt',['PardisoLLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1PardisoLLT.html',1,'Eigen']]],
  ['pardisolu',['PardisoLU',['http://eigen.tuxfamily.org/dox/classEigen_1_1PardisoLU.html',1,'Eigen']]],
  ['partialpivlu',['PartialPivLU',['http://eigen.tuxfamily.org/dox/classEigen_1_1PartialPivLU.html',1,'Eigen']]],
  ['partialreduxexpr',['PartialReduxExpr',['http://eigen.tuxfamily.org/dox/classEigen_1_1PartialReduxExpr.html',1,'Eigen']]],
  ['pastixldlt',['PastixLDLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1PastixLDLT.html',1,'Eigen']]],
  ['pastixllt',['PastixLLT',['http://eigen.tuxfamily.org/dox/classEigen_1_1PastixLLT.html',1,'Eigen']]],
  ['pastixlu',['PastixLU',['http://eigen.tuxfamily.org/dox/classEigen_1_1PastixLU.html',1,'Eigen']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::money_get']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::moneypunct']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::money_put']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::moneypunct_byname']]],
  ['pattern',['pattern',['http://en.cppreference.com/w/cpp/locale/money_base.html',1,'std::money_base']]],
  ['periodicstatusreportmhrwstatscollector',['PeriodicStatusReportMHRWStatsCollector',['../class_tomographer_1_1_periodic_status_report_m_h_r_w_stats_collector.html',1,'Tomographer']]],
  ['permutationbase',['PermutationBase',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationBase.html',1,'Eigen']]],
  ['permutationbase_3c_20permutationmatrix_3c_20sizeatcompiletime_2c_20maxsizeatcompiletime_2c_20indextype_20_3e_20_3e',['PermutationBase&lt; PermutationMatrix&lt; SizeAtCompileTime, MaxSizeAtCompileTime, IndexType &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationBase.html',1,'Eigen']]],
  ['permutationbase_3c_20permutationwrapper_3c_20_5findicestype_20_3e_20_3e',['PermutationBase&lt; PermutationWrapper&lt; _IndicesType &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationBase.html',1,'Eigen']]],
  ['permutationmatrix',['PermutationMatrix',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationMatrix.html',1,'Eigen']]],
  ['permutationwrapper',['PermutationWrapper',['http://eigen.tuxfamily.org/dox/classEigen_1_1PermutationWrapper.html',1,'Eigen']]],
  ['peta',['peta',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['pico',['pico',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['piecewise_5fconstant_5fdistribution',['piecewise_constant_distribution',['http://en.cppreference.com/w/cpp/numeric/random/piecewise_constant_distribution.html',1,'std']]],
  ['piecewise_5fconstruct_5ft',['piecewise_construct_t',['http://en.cppreference.com/w/cpp/utility/piecewise_construct_t.html',1,'std']]],
  ['piecewise_5flinear_5fdistribution',['piecewise_linear_distribution',['http://en.cppreference.com/w/cpp/numeric/random/piecewise_linear_distribution.html',1,'std']]],
  ['placeholders',['placeholders',['http://en.cppreference.com/w/cpp/utility/functional/placeholders.html',1,'std']]],
  ['plainobjectbase',['PlainObjectBase',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plainobjectbase_3c_20array_3c_20_5fscalar_2c_20_5frows_2c_20_5fcols_2c_20_5foptions_2c_20_5fmaxrows_2c_20_5fmaxcols_20_3e_20_3e',['PlainObjectBase&lt; Array&lt; _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plainobjectbase_3c_20array_3c_20counttype_2c_20eigen_3a_3adynamic_2c_201_2c_20_5foptions_2c_20_5fmaxrows_2c_20_5fmaxcols_20_3e_20_3e',['PlainObjectBase&lt; Array&lt; CountType, Eigen::Dynamic, 1, _Options, _MaxRows, _MaxCols &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plainobjectbase_3c_20array_3c_20intfreqtype_2c_20eigen_3a_3adynamic_2c_201_2c_200_2c_20fixedmaxparamlist_2c_201_20_3e_20_3e',['PlainObjectBase&lt; Array&lt; IntFreqType, Eigen::Dynamic, 1, 0, FixedMaxParamList, 1 &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plainobjectbase_3c_20matrix_3c_20_5fscalar_2c_20_5frows_2c_20_5fcols_2c_20_5foptions_2c_20_5fmaxrows_2c_20_5fmaxcols_20_3e_20_3e',['PlainObjectBase&lt; Matrix&lt; _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plainobjectbase_3c_20matrix_3c_20typename_20dmtypes_3a_3arealscalar_2c_20eigen_3a_3adynamic_2c_20dmtypes_3a_3afixeddim2_2c_20eigen_3a_3arowmajor_2c_20fixedmaxparamlist_2c_20dmtypes_3a_3afixeddim2_20_3e_20_3e',['PlainObjectBase&lt; Matrix&lt; typename DMTypes::RealScalar, Eigen::Dynamic, DMTypes::FixedDim2, Eigen::RowMajor, FixedMaxParamList, DMTypes::FixedDim2 &gt; &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1PlainObjectBase.html',1,'Eigen']]],
  ['plus',['plus',['http://en.cppreference.com/w/cpp/utility/functional/plus.html',1,'std']]],
  ['pointer_5fsafety',['pointer_safety',['http://en.cppreference.com/w/cpp/memory/gc/pointer_safety.html',1,'std']]],
  ['pointer_5ftraits',['pointer_traits',['http://en.cppreference.com/w/cpp/memory/pointer_traits.html',1,'std']]],
  ['poisson_5fdistribution',['poisson_distribution',['http://en.cppreference.com/w/cpp/numeric/random/poisson_distribution.html',1,'std']]],
  ['predstatusreportmhrwstatscollector',['PredStatusReportMHRWStatsCollector',['../class_tomographer_1_1_pred_status_report_m_h_r_w_stats_collector.html',1,'Tomographer']]],
  ['priority_5fqueue',['priority_queue',['http://en.cppreference.com/w/cpp/container/priority_queue.html',1,'std']]],
  ['productreturntype',['ProductReturnType',['http://eigen.tuxfamily.org/dox/structEigen_1_1ProductReturnType.html',1,'Eigen']]],
  ['promise',['promise',['http://en.cppreference.com/w/cpp/thread/promise.html',1,'std']]],
  ['ptrdiff_5ft',['ptrdiff_t',['http://en.cppreference.com/w/cpp/types/ptrdiff_t.html',1,'std']]],
  ['purifdisttorefcalculator',['PurifDistToRefCalculator',['../class_tomographer_1_1_dense_d_m_1_1_t_space_1_1_purif_dist_to_ref_calculator.html',1,'Tomographer::DenseDM::TSpace']]],
  ['pyfetchedexception',['PyFetchedException',['../classtpy_1_1_py_fetched_exception.html',1,'tpy']]],
  ['pylogger',['PyLogger',['../classtpy_1_1_py_logger.html',1,'tpy']]],
  ['pymhwalkerparamstodict',['PyMHWalkerParamsToDict',['../structtpy_1_1_py_m_h_walker_params_to_dict.html',1,'tpy']]],
  ['pymhwalkerparamstodict_3c_20tomographer_3a_3amhwalkerparamsstepsize_3c_20steprealtype_20_3e_20_3e',['PyMHWalkerParamsToDict&lt; Tomographer::MHWalkerParamsStepSize&lt; StepRealType &gt; &gt;',['../structtpy_1_1_py_m_h_walker_params_to_dict_3_01_tomographer_1_1_m_h_walker_params_step_size_3_01_step_real_type_01_4_01_4.html',1,'tpy']]],
  ['pystatusreportaddworkerdatafields',['PyStatusReportAddWorkerDataFields',['../structtpy_1_1_py_status_report_add_worker_data_fields.html',1,'tpy']]],
  ['pystatusreportaddworkerdatafields_3c_20tomographer_3a_3amhrwtasks_3a_3amhrandomwalktask_3c_20cdata_2c_20rng_20_3e_20_3e',['PyStatusReportAddWorkerDataFields&lt; Tomographer::MHRWTasks::MHRandomWalkTask&lt; CData, Rng &gt; &gt;',['../structtpy_1_1_py_status_report_add_worker_data_fields_3_01_tomographer_1_1_m_h_r_w_tasks_1_1_m_hc3aa0bf498c92a6d5aa321f181274958.html',1,'tpy']]]
];
