var searchData=
[
  ['random_5faccess_5fiterator_5ftag',['random_access_iterator_tag',['http://en.cppreference.com/w/cpp/iterator/iterator_tags.html',1,'std']]],
  ['random_5fdevice',['random_device',['http://en.cppreference.com/w/cpp/numeric/random/random_device.html',1,'std']]],
  ['randomwalkbase',['RandomWalkBase',['../struct_tomographer_1_1_random_walk_base.html',1,'Tomographer']]],
  ['range_5ferror',['range_error',['http://en.cppreference.com/w/cpp/error/range_error.html',1,'std']]],
  ['rank',['rank',['http://en.cppreference.com/w/cpp/types/rank.html',1,'std']]],
  ['ranlux24',['ranlux24',['http://en.cppreference.com/w/cpp/numeric/random/discard_block_engine.html',1,'std']]],
  ['ranlux24_5fbase',['ranlux24_base',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['ranlux48',['ranlux48',['http://en.cppreference.com/w/cpp/numeric/random/discard_block_engine.html',1,'std']]],
  ['ranlux48_5fbase',['ranlux48_base',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['ratio',['ratio',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['ratio_5fadd',['ratio_add',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_add.html',1,'std']]],
  ['ratio_5fdivide',['ratio_divide',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_divide.html',1,'std']]],
  ['ratio_5fequal',['ratio_equal',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_equal.html',1,'std']]],
  ['ratio_5fgreater',['ratio_greater',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_greater.html',1,'std']]],
  ['ratio_5fgreater_5fequal',['ratio_greater_equal',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_greater_equal.html',1,'std']]],
  ['ratio_5fless',['ratio_less',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_less.html',1,'std']]],
  ['ratio_5fless_5fequal',['ratio_less_equal',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_less_equal.html',1,'std']]],
  ['ratio_5fmultiply',['ratio_multiply',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_multiply.html',1,'std']]],
  ['ratio_5fnot_5fequal',['ratio_not_equal',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_not_equal.html',1,'std']]],
  ['ratio_5fsubtract',['ratio_subtract',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_subtract.html',1,'std']]],
  ['raw_5fstorage_5fiterator',['raw_storage_iterator',['http://en.cppreference.com/w/cpp/memory/raw_storage_iterator.html',1,'std']]],
  ['realqz',['RealQZ',['http://eigen.tuxfamily.org/dox/classEigen_1_1RealQZ.html',1,'Eigen']]],
  ['realschur',['RealSchur',['http://eigen.tuxfamily.org/dox/classEigen_1_1RealSchur.html',1,'Eigen']]],
  ['recursive_5fmutex',['recursive_mutex',['http://en.cppreference.com/w/cpp/thread/recursive_mutex.html',1,'std']]],
  ['recursive_5ftimed_5fmutex',['recursive_timed_mutex',['http://en.cppreference.com/w/cpp/thread/recursive_timed_mutex.html',1,'std']]],
  ['ref',['Ref',['http://eigen.tuxfamily.org/dox/classEigen_1_1Ref.html',1,'Eigen']]],
  ['reference',['reference',['http://en.cppreference.com/w/cpp/utility/bitset/reference.html',1,'std::bitset']]],
  ['reference_5fwrapper',['reference_wrapper',['http://en.cppreference.com/w/cpp/utility/functional/reference_wrapper.html',1,'std']]],
  ['regex',['regex',['http://en.cppreference.com/w/cpp/regex/basic_regex.html',1,'std']]],
  ['regex_5ferror',['regex_error',['http://en.cppreference.com/w/cpp/regex/regex_error.html',1,'std']]],
  ['regex_5fiterator',['regex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['regex_5ftoken_5fiterator',['regex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['regex_5ftraits',['regex_traits',['http://en.cppreference.com/w/cpp/regex/regex_traits.html',1,'std']]],
  ['remove_5fall_5fextents',['remove_all_extents',['http://en.cppreference.com/w/cpp/types/remove_all_extents.html',1,'std']]],
  ['remove_5fconst',['remove_const',['http://en.cppreference.com/w/cpp/types/remove_cv.html',1,'std']]],
  ['remove_5fcv',['remove_cv',['http://en.cppreference.com/w/cpp/types/remove_cv.html',1,'std']]],
  ['remove_5fextent',['remove_extent',['http://en.cppreference.com/w/cpp/types/remove_extent.html',1,'std']]],
  ['remove_5fpointer',['remove_pointer',['http://en.cppreference.com/w/cpp/types/remove_pointer.html',1,'std']]],
  ['remove_5freference',['remove_reference',['http://en.cppreference.com/w/cpp/types/remove_reference.html',1,'std']]],
  ['remove_5fvolatile',['remove_volatile',['http://en.cppreference.com/w/cpp/types/remove_cv.html',1,'std']]],
  ['replicate',['Replicate',['http://eigen.tuxfamily.org/dox/classEigen_1_1Replicate.html',1,'Eigen']]],
  ['result',['Result',['../struct_tomographer_1_1_value_histogram_with_binning_m_h_r_w_stats_collector_params_1_1_result.html',1,'Tomographer::ValueHistogramWithBinningMHRWStatsCollectorParams']]],
  ['result_5fof',['result_of',['http://en.cppreference.com/w/cpp/types/result_of.html',1,'std']]],
  ['reverse',['Reverse',['http://eigen.tuxfamily.org/dox/classEigen_1_1Reverse.html',1,'Eigen']]],
  ['reverse_5fiterator',['reverse_iterator',['http://en.cppreference.com/w/cpp/iterator/reverse_iterator.html',1,'std']]],
  ['rotation2d',['Rotation2D',['http://eigen.tuxfamily.org/dox/classEigen_1_1Rotation2D.html',1,'Eigen']]],
  ['rotationbase',['RotationBase',['http://eigen.tuxfamily.org/dox/classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20angleaxis_3c_20_5fscalar_20_3e_2c_203_20_3e',['RotationBase&lt; AngleAxis&lt; _Scalar &gt;, 3 &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20derived_2c_203_20_3e',['RotationBase&lt; Derived, 3 &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20map_3c_20const_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e_2c_203_20_3e',['RotationBase&lt; Map&lt; const Quaternion&lt; _Scalar &gt;, _Options &gt;, 3 &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20map_3c_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e_2c_203_20_3e',['RotationBase&lt; Map&lt; Quaternion&lt; _Scalar &gt;, _Options &gt;, 3 &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20quaternion_3c_20_5fscalar_2c_20_5foptions_20_3e_2c_203_20_3e',['RotationBase&lt; Quaternion&lt; _Scalar, _Options &gt;, 3 &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['rotationbase_3c_20rotation2d_3c_20_5fscalar_20_3e_2c_202_20_3e',['RotationBase&lt; Rotation2D&lt; _Scalar &gt;, 2 &gt;',['http://eigen.tuxfamily.org/dox/classEigen_1_1RotationBase.html',1,'Eigen']]],
  ['runtime_5ferror',['runtime_error',['http://en.cppreference.com/w/cpp/error/runtime_error.html',1,'std']]]
];
